name: bd14-despliegue-algo2
channels: 
  - defaults 
  - conda-forge 
dependencies: 
  - ipykernel
  - pip  
  - python=3.11.0
  - setuptools 
  - wheel 
  - poppler 
  - pip: 
    - fastapi==0.115.6
    - mlflow==2.18.0
    - pandas=2.2.2
    - numpy= 1.26.4
    - mlflow==2.18.0
    - scikit-learn=1.6.1

    
